version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - ../volumes/varlibmysql:/var/lib/mysql
      - ../volumes/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: cointracker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cointracker
      MYSQL_PASSWORD: changemeifyoucan
    ports:
      - "3306:3306"

  front:
    image: laalaguer/flask-dev
    depends_on:
       - db
    volumes:
      - ../../:/root/front-source
      - ./sites.cnf:/etc/nginx/sites-enabled/default
    working_dir: /root/front-source
    command: ["bash", "prod.run.sh"]
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: cointracker
      MYSQL_PASSWORD: changemeifyoucan
      MYSQL_DB_NAME: cointracker

